.editorconfig
.github/workflows/build.yml
.github/workflows/pullrequest.yml
.idea/dictionaries/bucketeer.xml
bucketeer/build.gradle
build.gradle
gradle/publish.gradle
sample/build.gradle

add workflows

---

.github/workflows/pullrequest.yml
.gitignore
commitlint.config.js

To enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) described in [CONTRIBUTING.md](https://github.com/bucketeer-io/android-client-sdk/blob/main/CONTRIBUTING.md), I've added commitlint check to CI.
failed: https://github.com/yshrsmz/android-client-sdk/actions/runs/3094712074/jobs/5008378745
succeeded: https://github.com/yshrsmz/android-client-sdk/actions/runs/3094871512/jobs/5008697637

ci: add commitlint job

---

.github/workflows/pr-title-validation.yml
.github/workflows/pullrequest.yml
.gitignore
commitlint.config.js

There are a few concerns regarding squash merge though:
- Single PR can not include multiple changelog entries
- This happens when a feature needs a library update.
- Admins need to add an optional body & footer(for example, breaking change) to final squash commit, which people easily forget.

ci: add PR title validation, remove commitlint

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClient.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClientImpl.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/Component.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/InteractorModule.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractor.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EvaluationForegroundTaskTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EventForegroundTaskTest.kt

As background polling depends on BKTClient instance, update listeners can be called when evaluations are updated from background tasks.

feat: evaluation update listener

---

bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientTest.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClient.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClientImpl.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTClientImplTest.kt

Because we refer to how to update the user attributes in the documentation, I think it will be better to use the word `update` instead of `set` for this case. 
The user attributes are set when the SDK is initialized, so it makes more sense to call as an update instead of a set.

feat: rename setUserAttributes interface to updateUserAttributes

---

bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientEventTest.kt
bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientTest.kt
bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientVariationTest.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTConfig.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/DataModule.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImpl.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTClientImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTConfigTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/TestHelpers.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EvaluationBackgroundTaskTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EvaluationForegroundTaskTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EventBackgroundTaskTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/scheduler/EventForegroundTaskTest.kt
sample/src/main/java/io/bucketeer/sample/App.kt

Because we use the api prefix in the `apiKey`, it will be better to match using the prefix in the endpoint config for easy understanding.

chore: rename endpoint config to apiEndpoint

---

gradle/libs.versions.toml
renovate.json

- update renovate.config to group Kotlin & ksp updates
- ksp has a dedicated artifact for each Kotlin version
- updated ksp to v1.7.22-1.0.8

ci: group Kotlin & ksp

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractor.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/db/EventDaoImpl.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/EventData.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/MetricsEventData.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTClientImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/MetricEventsUniqueKeyTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/db/EventDaoImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt
mocks/src/main/kotlin/io/bucketeer/sdk/android/mocks/events.kt

feat: prevent logging duplicate event data

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/database/DBOpenHelper.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/database/migration/Migration.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/database/migration/Migration1to2.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/database/migration/Migration2to3.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/DataModule.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/database/migration/MigrationTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/db/EvaluationDaoImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/db/EventDaoImplTest.kt
mocks/src/main/kotlin/io/bucketeer/sdk/android/mocks/evaluations.kt

Due to changes made in this [PR](https://github.com/bucketeer-io/android-client-sdk/pull/63) in the API response, some users are getting the following error.
```
Caused by: com.squareup.moshi.JsonDataException: Expected a string but was NUMBER at path $.reason.type
``` 
Because the reason object has changed, we must delete the old evaluation data in the evaluation table while upgrading the SDK.

fix: json data expection while converting reason type

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/EventCreators.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractor.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImpl.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/GetEvaluationsResult.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractorTest.kt

- When the response time is lower than 1 second, the latencySeconds field was set to `0` because the Long is an integer type.

fix: latency seconds field in metrics event

---

.idea/codeStyles/Project.xml
bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientEvaluationUpdateTests.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClientImpl.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTConfig.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/Constants.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/Component.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/di/InteractorModule.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractor.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/UserEvaluations.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/request/GetEvaluationsRequest.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClient.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImpl.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/UserEvaluationCondition.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTClientImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTConfigTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/db/EvaluationDaoImplTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt
mocks/src/main/kotlin/io/bucketeer/sdk/android/mocks/evaluations.kt

Should close #69 
- The server will return the new following fields in the response.
- forceUpdate: a boolean that tells the SDK to delete all the current data and save the latest evaluations from the response
- archivedFeatureIds: a list of feature flag ids that were archived on the console. All those feature flags must be deleted from the DB.
- The server will return the new following fields in the response.
- forceUpdate: a boolean that tells the SDK to delete all the current data and save the latest evaluations from the response
- archivedFeatureIds: a list of feature flag ids that were archived on the console. All those feature flags must be deleted from the DB.

perf: improve the network traffic and response time

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClient.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClientImpl.kt

Because the SDK uses the Lifecycle observer API, it must be called on the main thread.
However, the SDK should also be able to be initialized and destroyed on a non-main thread.
I have changed it to use the main handler when using the lifecycle observer.

chore: lose the main thread dependency in the initialize and destroy implementation

---

bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientEvaluationUpdateTests.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClientImpl.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTClientImplTest.kt

The E2E tests has been failed https://github.com/bucketeer-io/android-client-sdk/actions/runs/8165990303/job/22324131983
On the recents changes, we add some [codes](https://github.com/bucketeer-io/android-client-sdk/pull/129/files) to run on the `mainHandler.post{}` 
it will not run immediately. It will be scheduled and caused the NPE.

fix: null pointer exception when destroy and reinitialize the client SDK

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/database/SQLiteDatabaseExt.kt
gradle.properties
gradle/libs.versions.toml

Fixes https://github.com/bucketeer-io/android-client-sdk/issues/132
The sqlite-framework library 2.3.0 changed to Kotlin and introduced null checks to `LIMIT` field, causing NPE when initializing the SDK.
Before using the optional fields (having, groupBy, orderBy, limit), I added a null check and updated it to the latest version, 2.4.0.
---
This pull request primarily focuses on simplifying the `select` function in the `SQLiteDatabaseExt.kt` file and updating the version of `androidx-sqlite` in the `libs.versions.toml` file. The `select` function no longer includes parameters for `groupBy`, `having`, `orderBy`, and `limit`, and the `androidx-sqlite` version has been updated from `2.2.0` to `2.4.0`.
Here are the key changes:
Simplification of `select` function:
* …

fix: npe while initializing the sdk using sqlite-framework 2.3.0

---

sample/src/main/java/io/bucketeer/sample/App.kt
sample/src/main/java/io/bucketeer/sample/MainActivity.kt
sample/src/main/res/layout/activity_main.xml
sample/src/main/res/values/strings.xml

- No need to restart the sample app after changing the user, tag
- Update the demo app following up the documents
- Add a picker for selecting difference types of variants for testing (int, boolean, string, double, JSON)
<image src='https://github.com/bucketeer-io/android-client-sdk/assets/2597710/d796abea-f8d7-4fdc-8a90-81888796bbc4' width=300px>
<image src='https://github.com/bucketeer-io/android-client-sdk/assets/2597710/ed826e89-fbc2-4d39-b014-1c0740cf3453' width=300px>

chore: (sample app) enable switching user and tag during runtime.

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/EventCreators.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractor.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventCreatorsKtTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/event/EventInteractorTest.kt

When an invalid API key is used, the SDK will receive a 401 or 403 response. 
Since the key is invalid, the SDK was mistakenly generating error metrics to report these forbidden errors. 
However, because the key is invalid, the SDK is unable to report these events, leading to their accumulation. 
This buildup increases the number of event API requests, resulting in higher logging costs. 
To prevent this, we will skip generating error events for unauthorized (401) or forbidden (403) errors.

fix: skip generating error events for unauthorized or forbidden errors

---

bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientTest.kt
bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/BKTClientVariationTest.kt
bucketeer/src/androidTest/kotlin/io/bucketeer/sdk/android/e2e/TestHelpers.kt

This pull request addresses an issue with end-to-end test failures and skips checks on the featureVersion.

test: skip feature version checking in the e2e tests

---

.github/workflows/e2e.yml
sample/src/google-services.json

I found some issues when using the Android SDK as the reference for building the OpenFeature Kotlin Provider.
This pull request includes several CI/CD workflow changes and configuration files. The most important changes involve updating the environment for end-to-end (e2e) tests and modifying the `google-services.json` file
Changes:
- Before (25 mins): https://github.com/bucketeer-io/android-client-sdk/actions/runs/13896653761 
- After (6 mins): https://github.com/bucketeer-io/android-client-sdk/actions/runs/13899026054/job/38886143953?pr=218

ci: improve e2e test runner performance

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTClient.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTConfig.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/logger.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTConfigTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/LoggerHolderTest.kt

- Fixed a potential memory leak in LoggerHolder, which wasn't cleared when the client was destroyed.
- Fixed an issue where logs didn't work when building BKTConfig, due to LoggerHolder not being initialized at that time.

fix: prevent logger leaks when destroying and not working when building the client

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractor.kt
bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/remote/UserEvaluationCondition.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/evaluation/EvaluationInteractorTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt

This pull request updates the UserEvaluationCondition model by changing the type of the `userAttributesUpdated` field from `String` to `Boolean`.
Using a String previously caused the request to [fail](https://github.com/bucketeer-io/android-client-sdk/actions/runs/15337390704) after the backend changed how it parses the request.
Test E2e now [passed](https://github.com/bucketeer-io/android-client-sdk/actions/runs/15338842511)

fix: userAttributesUpdated being sent as string not a boolean

---

bucketeer/src/main/kotlin/io/bucketeer/sdk/android/BKTConfig.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/BKTConfigTest.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/TestHelpers.kt
bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt

- The `wrapperSdkVersion` is now required when setting `wrapperSdkSourceId` refs:[ js-sdk ](https://github.com/bucketeer-io/javascript-client-sdk/pull/224)
- Fixed build error when we merged the following [commit](https://github.com/bucketeer-io/android-client-sdk/commit/7c02cc057ae7bbda0757434a6d4f68136a0e56c4) before updating it with the main branch; there was an error. Some code conflicted and overwrote each other.

fix: wrapperSdkVersion is required when setting wrapperSdkSourceId.
